remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark"
title: "OBSESTRA"
tagline: "Observatorio Estratégico de Inteligencia Logística"
description: "Análisis de infraestructura fronteriza México-Estados Unidos"
url: "https://chackro.github.io"
baseurl: "/obsestra-web"
